version: '3.8'
services:
  web:
    build: .
    command: >
      sh -c "python Djirgo/manage.py makemigrations &&
             python Djirgo/manage.py migrate &&
             python Djirgo/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbit


  db:
    image: postgres:12.4-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  rabbit:
    restart: always
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "15672:15672"






